<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "sportresults"
 *
 * Auto generated by Extension Builder 2017-03-01
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'SoccerResults',
	'description' => 'Adds Teams, Groups and Results ',
	'category' => 'plugin',
	'author' => 'Michael Blunck',
	'author_email' => 'michael.blunck@phth.de',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '1',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '0.0.1',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);